services:
  postgres:
    image: postgres
    container_name: glovo_db
    ports:
      - 5522:5432
    environment:
      - POSTGRES_PASSWORD=glovopw
    volumes:
      - pgdata:/var/lib/postgresql/data
       
  redis:
    image: redis:latest
    container_name: glovo_redis
    ports:
      - 6379:6379
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data

  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
      - HTTP_USER=root
      - HTTP_PASSWORD=secret
    ports:
      - 8081:8081
    depends_on:
      - redis

  glovoapi:
    image: fesor24/glovoapi
    container_name: glovo_api
    build:
        context: .
        dockerfile: API/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Server=postgres:5432;Database=delivery-app;Port=5432;User Id=postgres;Password=glovopw;
      - ConnectionStrings__Redis=redis
      - Jwt__Issuer=http://glovo.com
      - Jwt__Key=BD295A96-A531-4656-BCDA-7FB3C84931E8
      - PayStack__Secret=your-paystack-secret
      - PayStack__Public=your-public-key
    ports:
      - 7050:80
    depends_on:
      - postgres
      - redis 
volumes:
  redis-data:
  pgdata:  